# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83e2900c08f7b0de771c31c9076e6290c05401a455e8456c3d624ea9848ac4059801d54380396aadc0b5435ca11336c9e94ff932a4af054f525e8d9ca8291963

test:
  secret_key_base: 665ce4e781ee53030eeb49cb52ad738b473c27256ec9c4f3a176d63fc1d06462d866d6f79205c4cb4a2b84fdd1319469ed0a51c5101f3573162f6f7f90a9645d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
